version: "3.9"
services:
  
  web:
    build: .
    container_name: "shorttrack_web"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - rabbitmq
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ACCESS_KEY=${ACCESS_KEY}
      - GEO_LOC_API_URL=${GEO_LOC_API_URL}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - QUEUE_NAME=${QUEUE_NAME}
    command: >
      uvicorn service.app.main:app --host 0.0.0.0 --port 8000
  
  worker:
    build: .
    container_name: "shorttrack_worker"
    depends_on:
      - db
      - redis
      - rabbitmq
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=5672
      - QUEUE_NAME=${QUEUE_NAME}
    command: >
      python service/worker/worker.py
  
  db:
    image: postgres:15
    container_name: "shorttrack_db"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  
  redis:
    image: redis:7
    container_name: "shorttrack_redis"
    ports:
      - "6379:6379"
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: "shorttrack_rabbitmq"
    ports:
      - "5672:5672"    
      - "15672:15672"  
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    
volumes:
  db_data: